### ISSUE TITLE
Not detecting mutations which can be seen in IGV

### ISSUE THREAD

**Issue by mbdabrowska1** [HKU-BAL/ClusterV#2]
Hi, I have an issue with ClusterV sometimes not detecting mutations that can be seen in IGV and are present at a relatively high allele frequency. In the following examples you can see that the mutation is clearly visible in IGV, but in the ClusterV report it doesn't seem to be called:

### **BARCODE19** 
RT:V106I mutation expected (GTA -> ATA at nucleotide 2411, NC_001802.1 reference)

![Screenshot from 2024-04-29 10-06-07](https://github.com/HKU-BAL/ClusterV/assets/26898140/3c550f72-6ed9-4fd5-865c-206a2ee275a3)

And the corresponding **report**:
![Screenshot from 2024-04-29 10-20-09](https://github.com/HKU-BAL/ClusterV/assets/26898140/2a0d0aee-27cd-419c-ae1f-13b373d4543c)

The **coverage** around the region isn't very high. Could this be causing the issue? I feel like it should still be seen in consensus unless I'm misunderstanding how Flye assembles the fragment.
![Screenshot from 2024-04-29 10-10-18](https://github.com/HKU-BAL/ClusterV/assets/26898140/3873140f-3b02-4bba-8767-017711f7b236)

### **BARCODE25** 

RT:E138A mutation expected (GAG -> GCG mutation at nucleotide 2508, NC_001802.1 reference)

![Screenshot from 2024-04-29 10-15-26](https://github.com/HKU-BAL/ClusterV/assets/26898140/3289af59-e632-4130-8aa3-a12b1f4bfb12)

Corresponding **report**:
![Screenshot from 2024-04-29 10-20-45](https://github.com/HKU-BAL/ClusterV/assets/26898140/210f76cf-4f3e-40b1-b57e-18b3a15de96c)

And **coverage**:
![Screenshot from 2024-04-29 10-16-12](https://github.com/HKU-BAL/ClusterV/assets/26898140/7677e4f4-b41c-4957-91f2-08906089fca0)

### **BARCODE43** - separate run 

RT:V106I mutation expected (GTA -> ATA at nucleotide 2411, NC_001802.1 reference):

![Screenshot from 2024-04-29 10-18-54](https://github.com/HKU-BAL/ClusterV/assets/26898140/90a90c5f-7ea7-4053-9c4d-73ead2e287b6)

**Report**: 
![Screenshot from 2024-04-29 10-21-17](https://github.com/HKU-BAL/ClusterV/assets/26898140/a333dffd-4520-4bd4-9a41-96992a9d2e1a)

**Coverage**:
![Screenshot from 2024-04-29 10-19-12](https://github.com/HKU-BAL/ClusterV/assets/26898140/d667264d-666b-4383-9e31-42e5ddf12cd9)

Any help with this would be greatly appreciated! Please let me know if you require the original files as I'm happy to share those via email.

**Comment by sujunhao** [comment]
Hi, 
The missing variants with high depth from output may have multiple causes.

It may be from (1) the missing calling from the variant caller, Clair-Ensemble model trained at Guppy5 data in ClusterV; (2) the read with variants are filtered, the original bam filtering reads with large indel are filtered in ClusterV, and the filtering process may filter read with your mentioned variants. the filtered file is in [YOUR INPUT FILE NAME]_f.bam.

For issue (2), adjusting the filtering setting in [--indel_l](https://github.com/HKU-BAL/ClusterV/blob/main/docs/options.md) may solve the issue.
For issue (1), we have extensively tested ClusterV to avoid this situation happening, however, when using data in different chemistry or from different basecalling from ONT data, the problem may exist. In this case, we need time and effort to evaluate and further adjust our variant calling model.

In case the adjustment of filtering does not solve the problem, Could you please share your files with me for further testing on my side? You can send it to my email, jhsu@connect.hku.hk, if needed.

Regards,
JH
