### ISSUE TITLE
Argument naming - Error during testing file analysis

### ISSUE THREAD

**Issue by SixEl27** [HKU-BAL/ClusterV#3]
Dear ClusterV dev, first of all, thank you for this nice tool.
During my installation (using conda) and testing of your tool (following the well-written README and using your test files), I encounter the following error in the 3rd step:

```
-----------------------------
[ ** STEP 3 ** ]get consensus and HIVDB report

Traceback (most recent call last):
  File "/home/user/app/ClusterV/cv.py", line 68, in <module>
    main()
  File "/home/user/app/ClusterV/cv.py", line 64, in main
    submodule.main()
  File "/home/user/app/ClusterV/cv/ClusterV.py", line 110, in main
    run_get_consensus(args)
  File "/home/user/app/ClusterV/cv/get_consensus.py", line 235, in run_get_consensus
    _n_of_read_for_consensus = args.n_of_read_for_consensus
AttributeError: 'Namespace' object has no attribute 'n_of_read_for_consensus'
```

I managed to fix it by changing the original line 66 in your script `ClusterV.py` from 
`parser.add_argument('--number_of_read_for_consense', type=int, default=1000,`
to
`parser.add_argument('--n_of_read_for_consensus', type=int, default=1000,`

I'm not a Python expert but this modification makes this argument be called in the same way in the different scripts (eg. `get_consensus.py`), and at least solved the issue for me.

As additional info, even if I don't think this has any impact, I also removed an extra space at the end of line 235 in the script `get_consensus.py`:
`_n_of_read_for_consensus = args.n_of_read_for_consensus `
to
`_n_of_read_for_consensus = args.n_of_read_for_consensus`

**Comment by aquaskyline** [comment]
Thank you so much for the report. Fixed accordingly in the main branch.
